import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

/**
 * Combines class names into a single string, merging duplicates and handling conditional classes.
 * This function is useful for dynamically constructing class names in React components.
 * @param inputs - An array of class names or conditional class names.
 * @returns A single string with all class names merged and duplicates removed.
 */
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

/**
 * Función para simular una demora en la ejecución
 * @param ms - Tiempo en milisegundos para la demora
 * @returns Una promesa que se resuelve después de la demora especificada
 * @example
 * // Uso de la función delay
 * await delay(1000); // Espera 1 segundo
 */
export const delay = (ms: number = 500) => new Promise((resolve) => setTimeout(resolve, ms));

// Export excel processor utilities
export * from './excel-processor';
export * from './excel';

/**
 * Creates a debounced version of a function that delays invoking until after wait milliseconds
 * have elapsed since the last time the debounced function was invoked.
 * @param func - The function to debounce
 * @param wait - The number of milliseconds to delay
 * @returns The debounced function
 * @example
 * const debouncedFn = debounce(() => console.log('Hello'), 1000);
 * debouncedFn(); // Will only execute after 1 second of no more calls
 */
export function debounce<T extends (...args: unknown[]) => unknown>(
  func: T,
  wait: number = 1500
): ((...args: Parameters<T>) => void) & { cancel: () => void } {
  // Use ReturnType<typeof setTimeout> so it works in both browser and Node environments
  let timeout: ReturnType<typeof setTimeout> | undefined;

  const executedFunction = (...args: Parameters<T>) => {
    const later = () => {
      if (timeout !== undefined) clearTimeout(timeout);
      func(...args);
    };

    if (timeout !== undefined) clearTimeout(timeout);
    timeout = setTimeout(later, wait);
  };

  // Expose a cancel method so callers can clear the pending timeout if needed
  executedFunction.cancel = () => {
    if (timeout !== undefined) {
      clearTimeout(timeout);
      timeout = undefined;
    }
  };

  return executedFunction as ((...args: Parameters<T>) => void) & { cancel: () => void };
}

/**
 * Función para analizar fechas en formato ISO 8601
 * Convierte una cadena de fecha en un objeto Date y devuelve una representación
 * en formato de fecha legible (por ejemplo, "Jan 1, 2020")
 * Si la fecha no es válida, devuelve undefined.
 * @param dateString - Cadena de fecha en formato ISO 8601
 * @return Una cadena de fecha formateada o undefined si la fecha es inválida
 */
export const parseDate = (dateString: string): string | undefined => {
  const date = new Date(dateString);
  return !isNaN(date.getTime())
    ? date.toLocaleDateString("es-AR", {
        year: "numeric",
        month: "short",
        day: "numeric",
      })
    : undefined;
};

/**
 * Función para simular una demora en la ejecución
 * @param ms - Tiempo en milisegundos para la demora
 * @returns Una promesa que se resuelve después de la demora especificada
 * @example
 * // Uso de la función delay
 * await sleep(1000); // Espera 1 segundo
 */
export const sleep = (ms: number = 500) => new Promise((resolve) => setTimeout(resolve, ms));

/**
 * Función para formatear un monto numérico a una cadena con formato monetario en pesos argentinos.
 * @param amount - Monto a formatear
 * @returns Una cadena con el monto formateado en pesos argentinos (por ejemplo, "$1.234,56")
 */
export const parseMoney = (amount: number | undefined): string => {
  if (amount === undefined) return "$0.00";
  return `$${amount.toLocaleString("es-AR", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;
};

/**
 * Array de categorías con códigos de productos
 * Cada objeto contiene un código de producto y su categoría correspondiente
 */
export const categorias = [
  { codigo: 1, categoria: "Panificados Fargo" },
  { codigo: 2, categoria: "Panificados Artesano" },
  { codigo: 3, categoria: "Panificados Fargo" },
  { codigo: 4, categoria: "Panificados Artesano" },
  { codigo: 5, categoria: "Panificados Bimbo" },
  { codigo: 6, categoria: "Panificados Lactal" },
  { codigo: 7, categoria: "Panificados Oroweat" },
  { codigo: 8, categoria: "Magdalenas" },
  { codigo: 9, categoria: "Magdalenas" },
  { codigo: 10, categoria: "Magdalenas" },
  { codigo: 11, categoria: "Magdalenas" },
  { codigo: 12, categoria: "Magdalenas" },
  { codigo: 13, categoria: "Magdalenas" },
  { codigo: 14, categoria: "Panificados Artesano" },
  { codigo: 15, categoria: "Panificados Lactal" },
  { codigo: 16, categoria: "Panificados Bimbo" },
  { codigo: 17, categoria: "Panificados Lactal" },
  { codigo: 18, categoria: "Panificados Bimbo" },
  { codigo: 21, categoria: "Rapiditas" },
  { codigo: 32, categoria: "Pan Bimbo" },
  { codigo: 34, categoria: "Pan Bimbo" },
  { codigo: 37, categoria: "Pan Bimbo" },
  { codigo: 38, categoria: "Magdalenas" },
  { codigo: 39, categoria: "Magdalenas" },
  { codigo: 42, categoria: "Panificados Lactal" },
  { codigo: 43, categoria: "Panificados Lactal" },
  { codigo: 45, categoria: "Panificados Lactal" },
  { codigo: 46, categoria: "Panificados Lactal" },
  { codigo: 50, categoria: "Takis" },
  { codigo: 51, categoria: "Takis" },
  { codigo: 53, categoria: "Takis" },
  { codigo: 54, categoria: "Takis" },
  { codigo: 55, categoria: "Takis" },
  { codigo: 56, categoria: "Takis" },
  { codigo: 57, categoria: "Takis" },
  { codigo: 59, categoria: "Takis" },
  { codigo: 60, categoria: "Takis" },
  { codigo: 64, categoria: "Panificados Bimbo" },
  { codigo: 71, categoria: "Snack" },
  { codigo: 72, categoria: "Snack" },
  { codigo: 73, categoria: "Snack" },
  { codigo: 74, categoria: "Snack" },
  { codigo: 75, categoria: "Snack" },
  { codigo: 76, categoria: "Snack" },
  { codigo: 77, categoria: "Snack" },
  { codigo: 78, categoria: "Snack" },
  { codigo: 79, categoria: "Snack" },
  { codigo: 80, categoria: "Snack" },
  { codigo: 81, categoria: "Snack" },
  { codigo: 82, categoria: "Snack" },
  { codigo: 83, categoria: "Snack" },
  { codigo: 84, categoria: "Snack" },
  { codigo: 85, categoria: "Snack" },
  { codigo: 86, categoria: "Snack" },
  { codigo: 87, categoria: "Snack" },
  { codigo: 88, categoria: "Snack" },
  { codigo: 89, categoria: "Snack" },
  { codigo: 90, categoria: "Snack" },
  { codigo: 91, categoria: "Snack" },
  { codigo: 92, categoria: "Snack" },
  { codigo: 93, categoria: "Snack" },
  { codigo: 94, categoria: "Snack" },
  { codigo: 95, categoria: "Snack" },
  { codigo: 96, categoria: "Snack" },
  { codigo: 97, categoria: "Snack" },
  { codigo: 98, categoria: "Snack" },
  { codigo: 99, categoria: "Snack" },
  { codigo: 100, categoria: "Snack" },
  { codigo: 101, categoria: "Snack" },
  { codigo: 102, categoria: "Snack" },
  { codigo: 103, categoria: "Snack" },
  { codigo: 104, categoria: "Snack" },
  { codigo: 105, categoria: "Snack" },
  { codigo: 106, categoria: "Snack" },
  { codigo: 107, categoria: "Snack" },
  { codigo: 108, categoria: "Snack" },
  { codigo: 109, categoria: "Snack" },
  { codigo: 110, categoria: "Consumo" },
  { codigo: 111, categoria: "Consumo" },
  { codigo: 112, categoria: "Consumo" },
  { codigo: 113, categoria: "Consumo" },
  { codigo: 114, categoria: "Consumo" },
  { codigo: 115, categoria: "Consumo" },
  { codigo: 116, categoria: "Consumo" },
  { codigo: 117, categoria: "Consumo" },
  { codigo: 118, categoria: "Consumo" },
  { codigo: 119, categoria: "Consumo" },
  { codigo: 120, categoria: "Consumo" },
  { codigo: 121, categoria: "Consumo" },
  { codigo: 122, categoria: "Consumo" },
  { codigo: 123, categoria: "Consumo" },
  { codigo: 124, categoria: "Consumo" },
  { codigo: 125, categoria: "Consumo" },
  { codigo: 126, categoria: "Consumo" },
  { codigo: 127, categoria: "Consumo" },
  { codigo: 128, categoria: "Consumo" },
  { codigo: 129, categoria: "Consumo" },
  { codigo: 130, categoria: "Consumo" },
  { codigo: 131, categoria: "Consumo" },
  { codigo: 132, categoria: "Consumo" },
  { codigo: 133, categoria: "Snack" },
  { codigo: 233, categoria: "Panificados Bimbo" },
  { codigo: 235, categoria: "Panificados Fargo" },
  { codigo: 243, categoria: "Dulces Budines" },
  { codigo: 333, categoria: "Panificados Bimbo" },
  { codigo: 422, categoria: "Panificados Bimbo" },
  { codigo: 425, categoria: "Panificados Bimbo" },
  { codigo: 428, categoria: "Panificados Bimbo" },
  { codigo: 443, categoria: "Panificados Fargo" },
  { codigo: 684, categoria: "Panificados Bimbo" },
  { codigo: 698, categoria: "Panificados Fargo" },
  { codigo: 768, categoria: "Dulces Budines" },
  { codigo: 863, categoria: "Panificados Bimbo" },
  { codigo: 885, categoria: "Panificados Bimbo" },
  { codigo: 1012, categoria: "Snack" },
  { codigo: 1013, categoria: "Snack" },
  { codigo: 1073, categoria: "Panificados Bimbo" },
  { codigo: 1143, categoria: "Panificados Lactal" },
  { codigo: 1254, categoria: "Panificados Fargo" },
  { codigo: 1316, categoria: "Snack" },
  { codigo: 1325, categoria: "Panificados Fargo" },
  { codigo: 1326, categoria: "Snack" },
  { codigo: 1331, categoria: "Panificados Fargo" },
  { codigo: 1332, categoria: "Snack" },
  { codigo: 1343, categoria: "Snack" },
  { codigo: 1353, categoria: "Snack" },
  { codigo: 1357, categoria: "Snack" },
  { codigo: 1362, categoria: "Snack" },
  { codigo: 1369, categoria: "Snack" },
  { codigo: 1372, categoria: "Snack" },
  { codigo: 1420, categoria: "Panificados Fargo" },
  { codigo: 1424, categoria: "Panificados Bimbo" },
  { codigo: 1426, categoria: "Panificados Bimbo" },
  { codigo: 1894, categoria: "Panificados Bimbo" },
  { codigo: 2004, categoria: "Dulces Madalenas" },
  { codigo: 2005, categoria: "Dulces Madalenas" },
  { codigo: 2006, categoria: "Dulces Madalenas" },
  { codigo: 2086, categoria: "Dulces Madalenas" },
  { codigo: 2312, categoria: "Snack" },
  { codigo: 2529, categoria: "Dulces Vainillas" },
  { codigo: 2554, categoria: "Panificados Bimbo" },
  { codigo: 2636, categoria: "Dulces Vainillas" },
  { codigo: 2697, categoria: "Dulces Vainillas" },
  { codigo: 2845, categoria: "Dulces Vainillas" },
  { codigo: 2927, categoria: "Panificados Lactal" },
  { codigo: 3102, categoria: "Snack" },
  { codigo: 3252, categoria: "Panificados Bimbo" },
  { codigo: 3344, categoria: "Dulces Budines" },
  { codigo: 3543, categoria: "Zenissimo" },
  { codigo: 3725, categoria: "Panificados Bimbo" },
  { codigo: 4292, categoria: "Panificados Bimbo" },
  { codigo: 4461, categoria: "Panificados Lactal" },
  { codigo: 4462, categoria: "Panificados Lactal" },
  { codigo: 4509, categoria: "Panificados Lactal" },
  { codigo: 5005, categoria: "Snack" },
  { codigo: 5220, categoria: "Panificados Lactal" },
  { codigo: 5295, categoria: "Panificados Lactal" },
  { codigo: 5454, categoria: "Consumo" },
  { codigo: 5520, categoria: "Panificados Lactal" },
  { codigo: 5954, categoria: "Panificados Bimbo" },
  { codigo: 7001, categoria: "Snack" },
  { codigo: 7138, categoria: "Dulces Madalenas" },
  { codigo: 7171, categoria: "Dulces Madalenas" },
  { codigo: 7245, categoria: "Dulces Madalenas" },
  { codigo: 7247, categoria: "Dulces Madalenas" },
  { codigo: 7249, categoria: "Dulces Madalenas" },
  { codigo: 7606, categoria: "Panificados Oroweat" },
  { codigo: 7609, categoria: "Panificados Oroweat" },
  { codigo: 7977, categoria: "Panificados Bimbo" },
  { codigo: 8053, categoria: "Snack" },
  { codigo: 8066, categoria: "Panificados Bimbo" },
  { codigo: 8400, categoria: "Panificados Bimbo" },
  { codigo: 9113, categoria: "Snack" },
  { codigo: 9135, categoria: "Snack" },
  { codigo: 9605, categoria: "Panificados Bimbo" },
  { codigo: 9983, categoria: "Panificados Bimbo" },
  { codigo: 20896, categoria: "Rapiditas" },
  { codigo: 21148, categoria: "Dulces Vainillas" },
  { codigo: 21478, categoria: "Tortillas" },
  { codigo: 21483, categoria: "Tortillas" },
  { codigo: 21701, categoria: "Panificados Fargo" },
  { codigo: 21703, categoria: "Panificados Fargo" },
  { codigo: 21705, categoria: "Panificados Fargo" },
  { codigo: 21707, categoria: "Panificados Fargo" },
  { codigo: 21711, categoria: "Panificados Fargo" },
  { codigo: 21783, categoria: "Panificados Fargo" },
  { codigo: 21784, categoria: "Dulces Vainillas" },
  { codigo: 22591, categoria: "Consumo" },
  { codigo: 23121, categoria: "Snack" },
  { codigo: 23418, categoria: "Tortillas" },
  { codigo: 24065, categoria: "Panificados Bimbo" },
  { codigo: 24203, categoria: "Consumo" },
  { codigo: 24218, categoria: "Consumo" },
  { codigo: 24222, categoria: "Consumo" },
  { codigo: 24237, categoria: "Consumo" },
  { codigo: 24238, categoria: "Consumo" },
  { codigo: 24418, categoria: "Panificados Bimbo" },
  { codigo: 24425, categoria: "Consumo" },
  { codigo: 24426, categoria: "Consumo" },
  { codigo: 25082, categoria: "Panificados Bimbo" },
  { codigo: 27006, categoria: "Panificados Bimbo" },
  { codigo: 27008, categoria: "Panificados Bimbo" },
  { codigo: 27010, categoria: "Panificados Bimbo" },
  { codigo: 27026, categoria: "Panificados Bimbo" },
  { codigo: 27028, categoria: "Panificados Bimbo" },
  { codigo: 27078, categoria: "Panificados Bimbo" },
  { codigo: 27233, categoria: "Panificados Bimbo" },
  { codigo: 27457, categoria: "Panificados Artesano" },
  { codigo: 27701, categoria: "Panificados Fargo" },
  { codigo: 28585, categoria: "Panificados Artesano" },
  { codigo: 32571, categoria: "Panificados Artesano" },
  { codigo: 39850, categoria: "Consumo" },
  { codigo: 39851, categoria: "Consumo" },
  { codigo: 45645, categoria: "Snack" },
  { codigo: 46327, categoria: "Panificados Artesano" },
  { codigo: 47723, categoria: "Panificados Artesano" },
  { codigo: 50415, categoria: "Panificados Bimbo" },
  { codigo: 54321, categoria: "Snack" },
  { codigo: 60892, categoria: "Panificados Bimbo" },
  { codigo: 60915, categoria: "Panificados Bimbo" },
  { codigo: 231321, categoria: "Snack" },
  { codigo: 254888, categoria: "Snack" },
  { codigo: 324413, categoria: "Panificados Fargo" },
  { codigo: 332698, categoria: "Snack" },
  { codigo: 365447, categoria: "Snack" },
  { codigo: 431321, categoria: "Budines" },
  { codigo: 503721, categoria: "Pan Dulce" },
  { codigo: 503969, categoria: "Panificados Artesano" },
  { codigo: 503994, categoria: "Panificados Artesano" },
  { codigo: 504142, categoria: "Panificados Lactal" },
  { codigo: 504143, categoria: "Panificados Fargo" },
  { codigo: 504144, categoria: "Panificados Bimbo" },
  { codigo: 504145, categoria: "Panificados Bimbo" },
  { codigo: 504147, categoria: "Pan Bimbo" },
  { codigo: 504148, categoria: "Pan Bimbo" },
  { codigo: 504149, categoria: "Panificados Fargo" },
  { codigo: 504150, categoria: "Panificados Fargo" },
  { codigo: 504151, categoria: "Pan Bimbo" },
  { codigo: 504152, categoria: "Pan Bimbo" },
  { codigo: 504153, categoria: "Panificados Fargo" },
  { codigo: 504154, categoria: "Dulces Budines" },
  { codigo: 504155, categoria: "Dulces Budines" },
  { codigo: 504156, categoria: "Dulces Budines" },
  { codigo: 504157, categoria: "Dulces Budines" },
  { codigo: 504158, categoria: "Dulces Budines" },
  { codigo: 504159, categoria: "Dulces Budines" },
  { codigo: 504160, categoria: "Dulces Budines" },
  { codigo: 504161, categoria: "Dulces Budines" },
  { codigo: 504162, categoria: "Dulces Budines" },
  { codigo: 504163, categoria: "Dulces Budines" },
  { codigo: 504255, categoria: "Panificados Artesano" },
  { codigo: 504398, categoria: "Pan Dulce" },
  { codigo: 504404, categoria: "Panificados Fargo" },
  { codigo: 504405, categoria: "Panificados Fargo" },
  { codigo: 504406, categoria: "Dulces Budines" },
  { codigo: 504407, categoria: "Dulces Budines" },
  { codigo: 504411, categoria: "Pan Dulce" },
  { codigo: 504412, categoria: "Pan Dulce" },
  { codigo: 504442, categoria: "Pan Dulce" },
  { codigo: 504443, categoria: "Pan Dulce" },
  { codigo: 504444, categoria: "Pan Dulce" },
  { codigo: 504445, categoria: "Pan Dulce" },
  { codigo: 504448, categoria: "Dulces Budines" },
  { codigo: 504450, categoria: "Dulces Budines" },
  { codigo: 504451, categoria: "Panificados Bimbo" },
  { codigo: 504459, categoria: "Pan Dulce" },
  { codigo: 504460, categoria: "Budines" },
  { codigo: 504475, categoria: "Consumo" },
  { codigo: 504476, categoria: "Consumo" },
  { codigo: 504477, categoria: "Consumo" },
  { codigo: 504509, categoria: "Panificados Bimbo" },
  { codigo: 504526, categoria: "Budines" },
  { codigo: 504587, categoria: "Zenissimo" },
  { codigo: 504589, categoria: "Dulces Budines" },
  { codigo: 505798, categoria: "Tortillas" },
  { codigo: 506405, categoria: "Tortillas" },
  { codigo: 506418, categoria: "Dulces Madalenas" },
  { codigo: 506419, categoria: "Dulces Madalenas" },
  { codigo: 506549, categoria: "Tortillas" },
  { codigo: 514458, categoria: "Snack" },
  { codigo: 515271, categoria: "Snack" },
  { codigo: 515272, categoria: "Snack" },
  { codigo: 515273, categoria: "Snack" },
  { codigo: 515274, categoria: "Snack" },
  { codigo: 515275, categoria: "Snack" },
  { codigo: 515276, categoria: "Snack" },
  { codigo: 515277, categoria: "Snack" },
  { codigo: 515278, categoria: "Snack" },
  { codigo: 515282, categoria: "Snack" },
  { codigo: 584778, categoria: "Magdalenas" },
  { codigo: 658465, categoria: "Snack" },
  { codigo: 658654, categoria: "Dulces Vainillas" },
  { codigo: 964511, categoria: "Tortillas" },
  { codigo: 964601, categoria: "Panificados Bimbo" },
  { codigo: 964638, categoria: "Panificados Bimbo" },
  { codigo: 964639, categoria: "Panificados Bimbo" },
  { codigo: 964641, categoria: "Panificados Bimbo" },
  { codigo: 964642, categoria: "Panificados Bimbo" },
  { codigo: 964645, categoria: "Panificados Bimbo" },
  { codigo: 964646, categoria: "Panificados Bimbo" },
  { codigo: 964647, categoria: "Panificados Bimbo" },
  { codigo: 964705, categoria: "Panificados Fargo" },
  { codigo: 964706, categoria: "Panificados Fargo" },
  { codigo: 964707, categoria: "Panificados Fargo" },
  { codigo: 964708, categoria: "Panificados Fargo" },
  { codigo: 964709, categoria: "Panificados Fargo" },
  { codigo: 964710, categoria: "Panificados Fargo" },
  { codigo: 964711, categoria: "Panificados Fargo" },
  { codigo: 964712, categoria: "Panificados Fargo" },
  { codigo: 964786, categoria: "Consumo" },
  { codigo: 964787, categoria: "Consumo" },
  { codigo: 964798, categoria: "Consumo" },
  { codigo: 964823, categoria: "Galletas" },
  { codigo: 964861, categoria: "Dulces Madalenas" },
  { codigo: 964862, categoria: "Dulces Madalenas" },
  { codigo: 964863, categoria: "Dulces Madalenas" },
  { codigo: 986554, categoria: "Takis" },
  { codigo: 5039695, categoria: "Panificados Bimbo" },
  { codigo: 5646543, categoria: "Panificados Bimbo" },
  { codigo: 6546513, categoria: "Dulces Vainillas" },
  { codigo: 6548989, categoria: "Dulces Madalenas" },
  { codigo: 6874364, categoria: "Dulces Vainillas" },
  { codigo: 8465143, categoria: "Snack" },
  { codigo: 9180921, categoria: "Dulces Budines" },
  { codigo: 32546543, categoria: "Consumo" },
  { codigo: 53413213, categoria: "Panificados Bimbo" },
  { codigo: 54645645, categoria: "Consumo" },
  { codigo: 65846846, categoria: "Consumo" },
  { codigo: 87638723, categoria: "Dulces Budines" },
  { codigo: 98766655, categoria: "Takis" },
  { codigo: 334555600, categoria: "Takis" },
  { codigo: 665690000, categoria: "Takis" },
  { codigo: 738399494, categoria: "Takis" },
  { codigo: 988585995, categoria: "Takis" },
  { codigo: 9383847748, categoria: "Takis" },
  { codigo: 66770000000000, categoria: "Takis" },
  { codigo: 768270000000000, categoria: "Dulces Budines" },
  { codigo: 6543.21, categoria: "Panificados Bimbo" },
];

/**
 * Array de marcas con códigos de productos
 * Cada objeto contiene un código de producto y su marca correspondiente
 */
export const marcas = [
  { codigo: 1, marca: "FARGO" },
  { codigo: 2, marca: "BIMBO" },
  { codigo: 3, marca: "FARGO" },
  { codigo: 4, marca: "ARTESANO" },
  { codigo: 5, marca: "BIMBO" },
  { codigo: 6, marca: "LACTAL" },
  { codigo: 7, marca: "ORO" },
  { codigo: 8, marca: "BIMBO" },
  { codigo: 9, marca: "BIMBO" },
  { codigo: 10, marca: "BIMBO" },
  { codigo: 11, marca: "BIMBO" },
  { codigo: 12, marca: "BIMBO" },
  { codigo: 13, marca: "BIMBO" },
  { codigo: 14, marca: "BIMBO" },
  { codigo: 15, marca: "LACTAL" },
  { codigo: 16, marca: "BIMBO" },
  { codigo: 17, marca: "LACTAL" },
  { codigo: 18, marca: "BIMBO" },
  { codigo: 21, marca: "BIMBO" },
  { codigo: 32, marca: "BIMBO" },
  { codigo: 34, marca: "BIMBO" },
  { codigo: 37, marca: "BIMBO" },
  { codigo: 38, marca: "BIMBO" },
  { codigo: 39, marca: "BIMBO" },
  { codigo: 42, marca: "LACTAL" },
  { codigo: 43, marca: "LACTAL" },
  { codigo: 45, marca: "LACTAL" },
  { codigo: 46, marca: "LACTAL" },
  { codigo: 50, marca: "TAKIS" },
  { codigo: 51, marca: "TAKIS" },
  { codigo: 53, marca: "TAKIS" },
  { codigo: 54, marca: "TAKIS" },
  { codigo: 55, marca: "TAKIS" },
  { codigo: 56, marca: "TAKIS" },
  { codigo: 57, marca: "TAKIS" },
  { codigo: 59, marca: "TAKIS" },
  { codigo: 60, marca: "TAKIS" },
  { codigo: 64, marca: "BIMBO" },
  { codigo: 71, marca: "Quento" },
  { codigo: 72, marca: "Quento" },
  { codigo: 73, marca: "Quento" },
  { codigo: 74, marca: "Quento" },
  { codigo: 75, marca: "Quento" },
  { codigo: 76, marca: "Quento" },
  { codigo: 77, marca: "Quento" },
  { codigo: 78, marca: "Quento" },
  { codigo: 79, marca: "Quento" },
  { codigo: 80, marca: "Quento" },
  { codigo: 81, marca: "Quento" },
  { codigo: 82, marca: "Quento" },
  { codigo: 83, marca: "Quento" },
  { codigo: 84, marca: "Quento" },
  { codigo: 85, marca: "Quento" },
  { codigo: 86, marca: "Quento" },
  { codigo: 87, marca: "Quento" },
  { codigo: 88, marca: "Quento" },
  { codigo: 89, marca: "Quento" },
  { codigo: 90, marca: "Quento" },
  { codigo: 91, marca: "Quento" },
  { codigo: 92, marca: "Quento" },
  { codigo: 93, marca: "Quento" },
  { codigo: 94, marca: "Quento" },
  { codigo: 95, marca: "Quento" },
  { codigo: 96, marca: "Quento" },
  { codigo: 97, marca: "Quento" },
  { codigo: 98, marca: "Quento" },
  { codigo: 99, marca: "Quento" },
  { codigo: 100, marca: "Quento" },
  { codigo: 101, marca: "Quento" },
  { codigo: 102, marca: "Quento" },
  { codigo: 103, marca: "Quento" },
  { codigo: 104, marca: "Quento" },
  { codigo: 105, marca: "Quento" },
  { codigo: 106, marca: "Quento" },
  { codigo: 107, marca: "Quento" },
  { codigo: 108, marca: "Quento" },
  { codigo: 109, marca: "Quento" },
  { codigo: 110, marca: "Camet" },
  { codigo: 111, marca: "Camet" },
  { codigo: 112, marca: "Camet" },
  { codigo: 113, marca: "Camet" },
  { codigo: 114, marca: "Camet" },
  { codigo: 115, marca: "Camet" },
  { codigo: 116, marca: "Dilexis" },
  { codigo: 117, marca: "Don Satur" },
  { codigo: 118, marca: "Don Satur" },
  { codigo: 119, marca: "Don Satur" },
  { codigo: 120, marca: "Don Satur" },
  { codigo: 121, marca: "Don Satur" },
  { codigo: 122, marca: "Don Satur" },
  { codigo: 123, marca: "9 de oro" },
  { codigo: 124, marca: "9 de oro" },
  { codigo: 125, marca: "9 de oro" },
  { codigo: 126, marca: "9 de oro" },
  { codigo: 127, marca: "9 de oro" },
  { codigo: 128, marca: "9 de oro" },
  { codigo: 129, marca: "9 de oro" },
  { codigo: 130, marca: "9 de oro" },
  { codigo: 131, marca: "Navarro" },
  { codigo: 132, marca: "Navarro" },
  { codigo: 133, marca: "PAPAS" },
  { codigo: 233, marca: "FARGO" },
  { codigo: 235, marca: "FARGO" },
  { codigo: 243, marca: "BIMBO" },
  { codigo: 333, marca: "BIMBO" },
  { codigo: 422, marca: "BIMBO" },
  { codigo: 425, marca: "FARGO" },
  { codigo: 428, marca: "BIMBO" },
  { codigo: 443, marca: "FARGO" },
  { codigo: 684, marca: "BIMBO" },
  { codigo: 698, marca: "FARGO" },
  { codigo: 768, marca: "BIMBO" },
  { codigo: 863, marca: "BIMBO" },
  { codigo: 885, marca: "BIMBO" },
  { codigo: 1012, marca: "PAPAS" },
  { codigo: 1013, marca: "PAPAS" },
  { codigo: 1073, marca: "BIMBO" },
  { codigo: 1143, marca: "LACTAL" },
  { codigo: 1254, marca: "FARGO" },
  { codigo: 1316, marca: "PAPAS" },
  { codigo: 1325, marca: "FARGO" },
  { codigo: 1326, marca: "PAPAS" },
  { codigo: 1331, marca: "FARGO" },
  { codigo: 1332, marca: "PAPAS" },
  { codigo: 1343, marca: "PAPAS" },
  { codigo: 1353, marca: "PAPAS" },
  { codigo: 1357, marca: "PAPAS" },
  { codigo: 1362, marca: "PAPAS" },
  { codigo: 1369, marca: "PAPAS" },
  { codigo: 1372, marca: "PAPAS" },
  { codigo: 1420, marca: "FARGO" },
  { codigo: 1424, marca: "BIMBO" },
  { codigo: 1426, marca: "BIMBO" },
  { codigo: 1894, marca: "BIMBO" },
  { codigo: 2004, marca: "BIMBO" },
  { codigo: 2005, marca: "BIMBO" },
  { codigo: 2006, marca: "BIMBO" },
  { codigo: 2086, marca: "BIMBO" },
  { codigo: 2312, marca: "OTROS" },
  { codigo: 2529, marca: "VALENTE" },
  { codigo: 2554, marca: "BIMBO" },
  { codigo: 2636, marca: "BIMBO" },
  { codigo: 2697, marca: "VALENTE" },
  { codigo: 2845, marca: "VALENTE" },
  { codigo: 2927, marca: "LACTAL" },
  { codigo: 3102, marca: "PAPAS" },
  { codigo: 3252, marca: "BIMBO" },
  { codigo: 3344, marca: "BIMBO" },
  { codigo: 3543, marca: "BIMBO" },
  { codigo: 3725, marca: "BRIOSH" },
  { codigo: 4292, marca: "BIMBO" },
  { codigo: 4461, marca: "LACTAL" },
  { codigo: 4462, marca: "LACTAL" },
  { codigo: 4509, marca: "LACTAL" },
  { codigo: 5005, marca: "PAPAS" },
  { codigo: 5220, marca: "LACTAL" },
  { codigo: 5295, marca: "LACTAL" },
  { codigo: 5454, marca: "BIMBO" },
  { codigo: 5520, marca: "LACTAL" },
  { codigo: 5954, marca: "BIMBO" },
  { codigo: 7001, marca: "PAPAS" },
  { codigo: 7138, marca: "VALENTE" },
  { codigo: 7171, marca: "VALENTE" },
  { codigo: 7245, marca: "VALENTE" },
  { codigo: 7247, marca: "VALENTE" },
  { codigo: 7249, marca: "VALENTE" },
  { codigo: 7606, marca: "OROWEAT" },
  { codigo: 7609, marca: "OROWEAT" },
  { codigo: 7977, marca: "BIMBO" },
  { codigo: 8053, marca: "PAPAS" },
  { codigo: 8066, marca: "BIMBO" },
  { codigo: 8400, marca: "BIMBO" },
  { codigo: 9113, marca: "PAPAS" },
  { codigo: 9135, marca: "PAPAS" },
  { codigo: 9605, marca: "BIMBO" },
  { codigo: 9983, marca: "BIMBO" },
  { codigo: 20896, marca: "BIMBO" },
  { codigo: 21148, marca: "BIMBO" },
  { codigo: 21478, marca: "BIMBO" },
  { codigo: 21483, marca: "BIMBO" },
  { codigo: 21701, marca: "FARGO" },
  { codigo: 21703, marca: "FARGO" },
  { codigo: 21705, marca: "FARGO" },
  { codigo: 21707, marca: "FARGO" },
  { codigo: 21711, marca: "FARGO" },
  { codigo: 21783, marca: "FARGO" },
  { codigo: 21784, marca: "BIMBO" },
  { codigo: 22591, marca: "OTROS" },
  { codigo: 23121, marca: "PAPAS" },
  { codigo: 23418, marca: "BIMBO" },
  { codigo: 24065, marca: "BIMBO" },
  { codigo: 24203, marca: "FARGO" },
  { codigo: 24218, marca: "FARGO" },
  { codigo: 24222, marca: "FARGO" },
  { codigo: 24237, marca: "FARGO" },
  { codigo: 24238, marca: "FARGO" },
  { codigo: 24418, marca: "BIMBO" },
  { codigo: 24425, marca: "FARGO" },
  { codigo: 24426, marca: "FARGO" },
  { codigo: 25082, marca: "BIMBO" },
  { codigo: 27006, marca: "BIMBO" },
  { codigo: 27008, marca: "BIMBO" },
  { codigo: 27010, marca: "BIMBO" },
  { codigo: 27026, marca: "BIMBO" },
  { codigo: 27028, marca: "BIMBO" },
  { codigo: 27078, marca: "BIMBO" },
  { codigo: 27233, marca: "BIMBO" },
  { codigo: 27457, marca: "ARTESANO" },
  { codigo: 27701, marca: "FARGO" },
  { codigo: 28585, marca: "ARTESANO" },
  { codigo: 32571, marca: "ARTESANO" },
  { codigo: 39850, marca: "BIMBO" },
  { codigo: 39851, marca: "BIMBO" },
  { codigo: 45645, marca: "PAPAS" },
  { codigo: 46327, marca: "ARTESANO" },
  { codigo: 47723, marca: "ARTESANO" },
  { codigo: 50415, marca: "BOH" },
  { codigo: 54321, marca: "PAPAS QUENTO" },
  { codigo: 60892, marca: "BIMBO" },
  { codigo: 60915, marca: "FARGO" },
  { codigo: 231321, marca: "PAPAS" },
  { codigo: 254888, marca: "PAPAS" },
  { codigo: 324413, marca: "FARGO" },
  { codigo: 332698, marca: "PAPAS QUENTO" },
  { codigo: 365447, marca: "OTROS" },
  { codigo: 431321, marca: "BIMBO" },
  { codigo: 503721, marca: "BIMBO" },
  { codigo: 503969, marca: "ARTESANO" },
  { codigo: 503994, marca: "ARTESANO" },
  { codigo: 504142, marca: "LACTAL" },
  { codigo: 504143, marca: "FARGO" },
  { codigo: 504144, marca: "BRIOSH" },
  { codigo: 504145, marca: "BOH" },
  { codigo: 504147, marca: "BRIOSH" },
  { codigo: 504148, marca: "BRIOSH" },
  { codigo: 504149, marca: "FARGO" },
  { codigo: 504150, marca: "FARGO" },
  { codigo: 504151, marca: "BRIOSH" },
  { codigo: 504152, marca: "BRIOSH" },
  { codigo: 504153, marca: "FARGO" },
  { codigo: 504154, marca: "BIMBO" },
  { codigo: 504155, marca: "VALENTE" },
  { codigo: 504156, marca: "VALENTE" },
  { codigo: 504157, marca: "VALENTE" },
  { codigo: 504158, marca: "VALENTE" },
  { codigo: 504159, marca: "BIMBO" },
  { codigo: 504160, marca: "BIMBO" },
  { codigo: 504161, marca: "VALENTE" },
  { codigo: 504162, marca: "BIMBO" },
  { codigo: 504163, marca: "BIMBO" },
  { codigo: 504255, marca: "ARTESANO" },
  { codigo: 504398, marca: "VALENTE" },
  { codigo: 504404, marca: "FARGO" },
  { codigo: 504405, marca: "FARGO" },
  { codigo: 504406, marca: "BIMBO" },
  { codigo: 504407, marca: "BIMBO" },
  { codigo: 504411, marca: "BIMBO" },
  { codigo: 504412, marca: "BIMBO" },
  { codigo: 504442, marca: "BIMBO" },
  { codigo: 504443, marca: "BIMBO" },
  { codigo: 504444, marca: "BIMBO" },
  { codigo: 504445, marca: "BIMBO" },
  { codigo: 504448, marca: "ARTESANO" },
  { codigo: 504450, marca: "ARTESANO" },
  { codigo: 504451, marca: "BIMBO" },
  { codigo: 504459, marca: "VALENTE" },
  { codigo: 504460, marca: "BIMBO" },
  { codigo: 504475, marca: "FARGO" },
  { codigo: 504476, marca: "FARGO" },
  { codigo: 504477, marca: "FARGO" },
  { codigo: 504509, marca: "BIMBO" },
  { codigo: 504526, marca: "BIMBO" },
  { codigo: 504587, marca: "BIMBO" },
  { codigo: 504589, marca: "ZENISSIMO" },
  { codigo: 505798, marca: "TIA ROSA" },
  { codigo: 506405, marca: "BIMBO" },
  { codigo: 506418, marca: "BIMBO" },
  { codigo: 506419, marca: "BIMBO" },
  { codigo: 506549, marca: "TIA ROSA" },
  { codigo: 514458, marca: "PAPAS" },
  { codigo: 515271, marca: "TAKIS" },
  { codigo: 515272, marca: "TAKIS" },
  { codigo: 515273, marca: "TAKIS" },
  { codigo: 515274, marca: "TAKIS" },
  { codigo: 515275, marca: "TAKIS" },
  { codigo: 515276, marca: "TAKIS" },
  { codigo: 515277, marca: "TAKIS" },
  { codigo: 515278, marca: "TAKIS" },
  { codigo: 515282, marca: "TAKIS" },
  { codigo: 584778, marca: "VALENTE" },
  { codigo: 658465, marca: "PAPAS" },
  { codigo: 658654, marca: "BIMBO" },
  { codigo: 964511, marca: "BIMBO" },
  { codigo: 964601, marca: "BIMBO" },
  { codigo: 964638, marca: "BIMBO" },
  { codigo: 964639, marca: "BIMBO" },
  { codigo: 964641, marca: "BIMBO" },
  { codigo: 964642, marca: "BIMBO" },
  { codigo: 964645, marca: "BIMBO" },
  { codigo: 964646, marca: "BIMBO" },
  { codigo: 964647, marca: "BIMBO" },
  { codigo: 964705, marca: "FARGO" },
  { codigo: 964706, marca: "FARGO" },
  { codigo: 964707, marca: "FARGO" },
  { codigo: 964708, marca: "FARGO" },
  { codigo: 964709, marca: "FARGO" },
  { codigo: 964710, marca: "FARGO" },
  { codigo: 964711, marca: "FARGO" },
  { codigo: 964712, marca: "FARGO" },
  { codigo: 964786, marca: "SABE BIEN" },
  { codigo: 964787, marca: "SABE BIEN" },
  { codigo: 964798, marca: "SABE BIEN" },
  { codigo: 964823, marca: "SALMAS" },
  { codigo: 964861, marca: "BIMBO" },
  { codigo: 964862, marca: "BIMBO" },
  { codigo: 964863, marca: "BIMBO" },
  { codigo: 986554, marca: "TAKIS" },
  { codigo: 5039695, marca: "ARTESANO" },
  { codigo: 5646543, marca: "FARGO" },
  { codigo: 6546513, marca: "BIMBO" },
  { codigo: 6548989, marca: "VALENTE" },
  { codigo: 6874364, marca: "BIMBO" },
  { codigo: 8465143, marca: "PAPAS QUENTO" },
  { codigo: 9180921, marca: "BIMBO" },
  { codigo: 32546543, marca: "BIMBO" },
  { codigo: 53413213, marca: "BIMBO" },
  { codigo: 54645645, marca: "BIMBO" },
  { codigo: 65846846, marca: "BIMBO" },
  { codigo: 87638723, marca: "BIMBO" },
  { codigo: 98766655, marca: "TAKIS" },
  { codigo: 334555600, marca: "TAKIS" },
  { codigo: 665690000, marca: "TAKIS" },
  { codigo: 738399494, marca: "TAKIS" },
  { codigo: 988585995, marca: "TAKIS" },
  { codigo: 9383847748, marca: "TAKIS" },
  { codigo: 66770000000000, marca: "TAKIS" },
  { codigo: 768270000000000, marca: "BIMBO" },
  { codigo: 6543.21, marca: "BOH" },
];

export const condicionIva = {
  "Responsable Inscripto": 1,
  "resp. inscripto": 1,
  "resp, inscripto": 1,
  "rep. Inscripto": 1,
  "resp inscripto": 1,
  "Exento": 3,
  "Consumidor Final": 4,
  "Monotributo": 6,
  "monotriburto": 6,
  "monitributo": 6,
  "motributo": 6,
};