[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Redirect all requests to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Force correct MIME types for JavaScript modules
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "*.mjs"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "*.jsx"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "*.ts"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "*.tsx"
  [headers.values]
    Content-Type = "text/javascript"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "max-age=31536000, immutable"